### ISSUE TITLE
feat: disable `id-length` rules

### ISSUE THREAD

**Issue by tony-go** [NodeSecure/eslint-config#17]
Hi 👋 

I saw in the last [pull request](https://github.com/NodeSecure/ci/pull/3) of @antoine-coulon that he disables the rule.

I confess that I'd like to disable it also a lot of time.

So I'd like to discuss it with the team.

**Comment by fraxken** [comment]
Ok for me. If someone want to contribute to this, then let's go :)

**Comment by fraxken** [comment]
@all-contributors please add @tony-go for code
